### ISSUE TITLE
테스트 코드 작성

### ISSUE THREAD

**Issue by ljy2855** [CSPCLAB/cspc_apply_server#23]
### TODO
기존 API 테스트를 위해 테스트 코드 작성

- [ ] auth module 테스트 코드 작성
- [ ] apply API 테스트 코드 작성

코드 구현 시, `unit test` , `api test` 에 대해 공부한 뒤 작성

**Comment by darami819** [comment]
이런 방식으로 하는 게 맞는지 한번 확인 부탁드립니다..
그리고 models.py에 있는 각 class에 있는 내용도 테스트 해야 하는 건지 잘 모르겠어요.
